### ISSUE TITLE
[Cub] Remove animations for `prefers-reduced-motion: reduced;`

### ISSUE THREAD

**Issue by mmaismma** [Hermit-Tools/Thumbnail-Maker#18]
**Description**
Cub's Contraption has minor animations. Animations can sometimes promote certain types of migraines. If the user has disabled system animations on their device, the website should remove the animations too.

**Possible solution(s)**
The prefers-reduced-motion CSS media feature is used to detect if the user has requested that the system minimize the amount of non-essential motion it uses.
```css
@media (prefers-reduced-motion) {
  body {
    animation: none!important;
    transition: none!important;
  }
}
```
